#pragma once

// clang-format off

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/TextWidget.hpp>

namespace RED4ext
{
namespace ink
{
struct __declspec(align(0x10)) TextInputWidget : ink::TextWidget
{
    static constexpr const char* NAME = "inkTextInputWidget";
    static constexpr const char* ALIAS = "inkTextInput";

    virtual void sub_230(uint64_t) override; // draws the caret

    uint8_t hasFocus; // 430
    uint8_t unk431; // 431 caret highlight?
    int32_t caretPosition; // 434
    uint32_t unk438; // 438 caret hightlight counter
    uint32_t maxLength; // 43C
    RED4ext::Handle<RED4ext::IScriptable> OnFocusReceivedCallback; // 440
    RED4ext::Handle<RED4ext::IScriptable> OnFocusLostCallback; // 450
    RED4ext::Handle<RED4ext::IScriptable> OnCharacterKeyCallback; // 460 processes ink::CharacterEvent
};
RED4EXT_ASSERT_SIZE(TextInputWidget, 0x470);
} // namespace ink
using inkTextInputWidget = ink::TextInputWidget;
using inkTextInput = ink::TextInputWidget;
} // namespace RED4ext

// clang-format on
